window.CCT_VOICE_LIBRARY={
  female1:{
    basePath:"audio/female1"
  },
  female2:{
    basePath:"audio/female2"
  },
  nathan:{
    basePath:"audio/nathan"
  },
  enhancednathan:{
    basePath:"audio/enhancednathan"
  }
};
