window.CCT_VOICE_LIBRARY={
  samantha:{
    basePath:"audio/samantha"
  },
  nathan:{
    basePath:"audio/nathan"
  },
  enhancednathan:{
    basePath:"audio/enhancednathan"
  },
  siri4:{
    basePath:"audio/siri4"
  }
};
